Repository MapColonies/exporter-trigger, pull requests merged in 2020-10, with the labels that each got.

#36 fix(dockerfile): add confd run
  build.sh
  dockerfile
  run.sh
Labels: bug

#37 feat(status): add path in router for getting exported jobs status
  confd/production.tmpl
  dockerfile
  docs/openapi3.yaml
  package-lock.json
  package.json
  src/controllers/getGeopackageExecutionStatus.ts
  src/model/executionStatusManagerConfig.ts
  src/routers/getGeopackageExecutionStatus.ts
  src/routers/global.ts
  src/status/executionStatusManager.ts
Labels: enhancement

#44 fix(execution status): change path for getting execution status
  docs/openapi3.yaml
  src/controllers/getGeopackageExecutionStatus.ts
  src/routers/global.ts
Labels: bug

#45 chore(uuid): generate uuid for taskId
  package-lock.json
  package.json
  src/commonStorage/commonStorageManager.ts
  src/controllers/exportGeopackage.ts
  src/controllers/getGeopackageExecutionStatus.ts
  src/kafka/manager.ts
  src/model/commonStorageConfig.ts
  src/model/executionStatusManagerConfig.ts
  src/model/exportRequest.ts
  src/model/exportStatusRequest.ts
  src/requests/urls.ts
  src/status/executionStatusManager.ts
Labels: enhancement

#46 feat(status response): add bbox to export status response
  src/model/exportStatusRequest.ts
Labels: enhancement

#47 docs(readme): update usage section
  readme.md
Labels: documentation

#48 chore: seperate logic from controllers
  docs/openapi3.yaml
  src/commonStorage/commonStorageManager.ts
  src/controllers/exportGeopackage.ts
  src/controllers/getGeopackageExecutionStatus.ts
  src/controllers/swagger.ts
  src/kafka/manager.ts
  src/middleware/ErrorHandler.ts
  src/model/exportRequest.ts
  src/model/exportStatusRequest.ts
  src/model/kafkaConfig.ts
  src/requests/errors/errors.ts
  src/requests/errors/kafka.ts
  src/requests/errors/status.ts
  src/routers/getGeopackageExecutionStatus.ts
  src/serverBuilder.ts
  src/util/exportDataString.ts
  src/util/outboundRequestToExport.ts
Labels: enhancement

#49 chore(save params): add taskId query param to save request
  src/commonStorage/commonStorageManager.ts
Labels: enhancement

#53 fix(swagger port): check swagger config before using default environm…
  src/controllers/swagger.ts
Labels: bug

#55 fix(export save): move data from axios config body to body data
  src/commonStorage/commonStorageManager.ts
Labels: bug

#59 chore(utc date): create date as UTC
  src/model/exportStatusRequest.ts
Labels: enhancement
